# Use the same base image
FROM python:3.11-slim

# Set the working directory for the test container
WORKDIR /tests

# Copy the requirements.txt for testing into the container
COPY requirements_test.txt .

# Install the testing dependencies
RUN pip install --no-cache-dir -r requirements_test.txt

# Copy the test suite and application code into the container
COPY . .

# Run pytest tests on container startup
CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
