# Use the same base image
FROM python:3.11-slim

# Set the working directory for the test container
WORKDIR /tests

# Copy the requirements.txt for testing into the container
COPY requirements_test.txt .

# Install the testing dependencies
RUN pip install --no-cache-dir -r requirements_test.txt

# Copy the test suite and application code into the container
COPY . .

# Run pytest tests on container startup
#CMD ["pytest", "--html=/tests/report/report.html", "--self-contained-html", "--cov=forex_api", "--cov-report=html", "--maxfail=1", "--disable-warnings", "-q"]
CMD ["/bin/bash", "-c", "pytest --self-contained-html --cov=forex_api --cov-report=html && ls -lsa && sleep 5 && ls -lsa"]


