services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile # Build the API server from the Dockerfile in the current directory
    ports:
      - "8081:8081" # Expose FastAPI app on port 8081
    environment:
      - BASE_URL=${BASE_URL}
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ["uvicorn", "forex_api.main:app", "--host", "0.0.0.0", "--port", "8081"]
    healthcheck:
      test: ["CMD", "curl", "-f", "${BASE_URL}/health"]  # Health check command
      interval: 600s
      retries: 1
      start_period: 3s
      timeout: 5s
    networks:
      - app-network
    depends_on:
      - db # Ensure the database is started before the API server

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app-network

  test-suite:
    build:
      context: .
      dockerfile: Dockerfile_test  # Build the test container from Dockerfile.test
    depends_on:
      api-server: # Ensure the API server starts before the tests run
        condition: service_healthy
    environment:
      - API_URL=${API_URL} # Point tests to the API server container
    working_dir: /tests
    command: ["/bin/bash", "-c", "pytest --api-url=${API_URL} --html=/tests/reports/report.html --self-contained-html --cov=forex_api --cov-report=html"]
    volumes:
      - ./reports:/tests/reports
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

